feat: support for tweakpane v4
0b5vr/tweakpane-plugin-profiler pull request #1
Opened 2023-09-22 00:05 UTC by kitschpatrol

Hi, similar to [this PR](https://github.com/0b5vr/tweakpane-plugin-rotation/pull/2) on your other plugin, I've updated the Profiler for compatibility with Tweakpane 4.x.

More involved changes were required than for the Rotation plugin, due to more significant shifts in Tweakpane 4's  blade implementation.

Thanks again for making these useful tools open-source.

2023-11-09 01:48 UTC, 0b5vr commented
I will review this as well, thanks a lot! + I'm sorry to be unaware for a while 🙇

2023-11-09 14:54 UTC, 0b5vr commented on src/ProfilerApi.ts
> +export class ProfilerBladeApi extends BladeApi<ProfilerBladeController> {
Feels like `ProfilerBladeApi` is more appropriate if we follow the name of the base class. Why was the file name changed?

2023-11-09 14:55 UTC, 0b5vr commented on src/ProfilerController.ts
> +export class ProfilerController implements Controller<ProfilerView> {
huhh, now `BladeController` and `Controller` are different, I got it. Or is this a concept that the v3 already had?

2023-11-09 15:00 UTC, 0b5vr commented on src/ProfilerController.ts
> +export class ProfilerController implements Controller<ProfilerView> {
Ahh, I might've simply not been aware of `BladeController` at the moment I implement this. Looks like a very nice improvement.

2023-11-09 15:03 UTC, 0b5vr commented on src/ProfilerBladeController.ts
> +  public readonly valueController: ProfilerController;
It's called `valueController` since it is `valueController` even in `LabelController`. ✅

2023-11-09 15:09 UTC, 0b5vr requested changes
The filename `ProfilerApi.ts` is the only issue I want to check before merge!

2023-11-09 16:42 UTC, kitschpatrol commented on src/ProfilerApi.ts
> +export class ProfilerBladeApi extends BladeApi<ProfilerBladeController> {
Oops yes `ProfilerBladeApi.ts` makes more sense.

2023-11-10 02:40 UTC, 0b5vr approved these changes
Thanks a lot!

2023-11-10 03:11 UTC, merged